### PR TITLE
Fix issues with icons not loaded

### PR DESCRIPTION
**Pull request by igor-baiborodine**
I added a GitHub action to automate the deployment to GitHub Pages.

### CODE REVIEW

**Comment by igor-baiborodine** [comment]
After merging this PR make sure that in the configuration for GitHub Pages you point to the `root`:

image

**Comment by gitaeron** [comment]
uh... Here's the same issue happened...

I just merged this pull request, and use `git pull origin main -f` with my local Repo.

And then, use `hugo` in my local **branch main** to generate **public/**, I'm using `Git Bash`  in windows10 22H2.
image

Final I commit it to **branch page**.

And I always point to the root in github page setting.....
image

But it just happened.... I was already empty the cache and refresh the page in chrome... I can't figure out why..
image

**Comment by gitaeron** [comment]
> After merging this pull request make sure that in the configuration for GitHub Pages of **your** repository you point to the `root`:
> 
> image

uh... Here's the same issue happened...

I just merged this pull request, and use `git pull origin main -f` with my local Repo.

And then, use `hugo` in my local **branch main** to generate **public/**, I'm using `Git Bash`  in windows10 22H2.
image

Final I commit it to **branch page**.

And I always point to the root in github page setting.....
image

But it just happened.... I was already empty the cache and refresh the page in chrome... I can't figure out why..
image

**Comment by igor-baiborodine** [comment]
@gitaeron , I will make another pull request. I think, I found the reason.

**Pull request merged**
